### ISSUE TITLE
full example in documentation

### ISSUE THREAD

**Issue by stefanleh** [lkishalmi/gradle-gatling-plugin#4]
Hello, could you please add a full example to the documentation?

at the moment i struggle to define the correct directories:

	:gatling
	Exception in thread "main" java.nio.file.NoSuchFileException: .\target\test-classes
	        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	        at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
	        at java.nio.file.Files.newDirectoryStream(Files.java:457)
	        at io.gatling.core.util.PathHelper$RichPath$.deepListAux$1(PathHelper.scala:99)
	        at io.gatling.core.util.PathHelper$RichPath$.deepList$extension(PathHelper.scala:105)
	        at io.gatling.core.util.PathHelper$RichPath$.deepFiles$extension(PathHelper.scala)
	        at io.gatling.app.classloader.SimulationClassLoader.simulationClasses(SimulationClassLoader.scala:55)
	        at io.gatling.app.Gatling.loadSimulations(Gatling.scala:92)
	        at io.gatling.app.Gatling.start(Gatling.scala:70)
	        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:59)
	        at io.gatling.app.Gatling$.main(Gatling.scala:44)
	        at io.gatling.app.Gatling.main(Gatling.scala)
	:gatling FAILED

I've defined in my gradle.properties:

	gatling.simulationsDir=gatling/simulations
	gatling.classesDir=gatling/classes

Best regards, Stefan

**Comment by eshepelyuk** [comment]
Exactly the same error happens to me.

**Comment by eshepelyuk** [comment]
Assuming `gatling` tests are located in `src/gatling/simulations` the following line added to `build.gradle` helps.

    tasks["gatling"].classesDir = tasks["gatlingCompile"].destinationDir
