### ISSUE TITLE
Having issues running gatling simulation with 3.0.2

### ISSUE THREAD

**Issue by mailtoshrb** [lkishalmi/gradle-gatling-plugin#78]
I have Update my project to latest version of this plugin, see build.gradle below, but when i try to run from root folder
Default logback.xml and gatling.conf are  in src/gatling/resources folder

I tried running following from root with or without mentioned gatling simulations in build.gradle but same issue always
gradle gatlingRun-scenario.CompleteApplication
gradle gatlingRun - expected this to pick form build.gradle file

Both above giving following exception

> Task :gatlingRun-scenario.CompleteApplication
15:25:44.957 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: scenario.CompleteApplication
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class scenario.CompleteApplication could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.IllegalArgumentException: User defined Simulation class scenario.CompleteApplication could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.ClassNotFoundException: scenario.CompleteApplication
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 more

> Task :gatlingRun-scenario.CompleteApplication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gatlingRun-scenario.CompleteApplication'.
> Some simulations failed : scenario.CompleteApplication

>Build.gradle 

plugins {
    id "com.github.lkishalmi.gatling" version "3.0.2"
}
repositories {
    mavenCentral()
}
apply plugin: 'scala'
apply plugin: 'java'

dependencies {
    compile 'org.scala-lang:scala-library:2.11.8'
    //gatling 'io.gatling.highcharts:gatling-charts-highcharts:3.0.1'
}

gatling {
    simulations = [ 'scenario.CompleteApplication' ]
}

group 'com.techietester'
version '1.0-SNAPSHOT'

>my project structure
![image](https://user-images.githubusercontent.com/23381847/49234636-5810d980-f3f0-11e8-9776-58e6fa8415d8.png)

It used to work flawless with old version 0.4.1 but now it's not, Could some one please look into this and cofirm is this an issue in plugin side or not? 

Thanks,
Sree

**Comment by eshepelyuk** [comment]
Please read the plugin's documentation, [the section dedicated to simulation file location](https://github.com/lkishalmi/gradle-gatling-plugin#source-files-layout)

**Comment by mailtoshrb** [comment]
I have tried that in first place but it was throwing me other error

![image](https://user-images.githubusercontent.com/23381847/49235278-a70b3e80-f3f1-11e8-9e6a-fdaa62b16aa6.png)

>console output:
C:\Users\srbandla\IdeaProjects\gradle-gatling>gradle gatlingRun

> Task :compileGatlingScala
Pruning sources from previous analysis, due to incompatible CompileSetup.

> Task :compileGatlingScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGatlingScala'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by eshepelyuk** [comment]
Did you try to remove `scala` folder completely ?

**Comment by eshepelyuk** [comment]
BTW, gatling uses Scala 2.12, and you declared 2.11 explicitely. This may be the cause too.

**Comment by mailtoshrb** [comment]
I have quickly created a demo project just for this as i can't delete scal folder in my actual project as it has git init but the error seems not gone away. See gatling failures below:

>Console Output:
C:\Users\srbandla\gatling-demo>gradle gatlingRun
Starting a Gradle Daemon, 1 incompatible and 3 stopped Daemons could not be reused, use --status for details

> Task :compileGatlingScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
C:\Users\srbandla\gatling-demo\src\gatling\simulations\BasicSimulation.scala:8: value baseURL is not a member of io.gatling.http.protocol.HttpProtocolBuilder
  val httpConf = http.baseURL("https://api.football-data.org/")
                      ^
C:\Users\srbandla\gatling-demo\src\gatling\simulations\BasicSimulation1.scala:8: value baseURL is not a member of io.gatling.http.protocol.HttpProtocolBuilder
  val httpConf = http.baseURL("https://api.football-data.org/")
                      ^
two errors found

> Task :compileGatlingScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGatlingScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
1 actionable task: 1 executed

C:\Users\srbandla\gatling-demo>
C:\Users\srbandla\gatling-demo>
C:\Users\srbandla\gatling-demo>
C:\Users\srbandla\gatling-demo>gradle gatlingRun

> Task :compileGatlingScala
Pruning sources from previous analysis, due to incompatible CompileSetup.

> Task :gatlingRun
16:34:24.658 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: BasicSimulation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.ClassNotFoundException: BasicSimulation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 more
16:34:29.741 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: BasicSimulation1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation1 could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation1 could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.ClassNotFoundException: BasicSimulation1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 more

> Task :gatlingRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gatlingRun'.
> Some simulations failed : BasicSimulation, BasicSimulation1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
3 actionable tasks: 3 executed

C:\Users\srbandla\gatling-demo>
C:\Users\srbandla\gatling-demo>
C:\Users\srbandla\gatling-demo>
C:\Users\srbandla\gatling-demo>gradle gatlingRun-BasicSimulation

> Task :gatlingRun-BasicSimulation
16:35:47.675 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: BasicSimulation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.ClassNotFoundException: BasicSimulation
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 more

> Task :gatlingRun-BasicSimulation FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gatlingRun-BasicSimulation'.
> Some simulations failed : BasicSimulation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
3 actionable tasks: 1 executed, 2 up-to-date

C:\Users\srbandla\gatling-demo>gradle gatlingRun-BasicSimulation.scala

> Task :gatlingRun-BasicSimulation.scala
16:35:58.097 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.ClassNotFoundException: BasicSimulation.scala
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 common frames omitted
Wrapped by: java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation.scala could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Exception in thread "main" java.lang.IllegalArgumentException: User defined Simulation class BasicSimulation.scala could not be loaded
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:79)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$4(Selection.scala:84)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$3(Selection.scala:84)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig(Selection.scala:82)
        at io.gatling.app.Selection$Selector.$anonfun$selection$1(Selection.scala:52)
        at scala.Option.getOrElse(Option.scala:121)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:44)
        at io.gatling.app.Selection$.apply(Selection.scala:36)
        at io.gatling.app.Runner.run0(Runner.scala:74)
        at io.gatling.app.Runner.run(Runner.scala:61)
        at io.gatling.app.Gatling$.start(Gatling.scala:74)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
        at io.gatling.app.Gatling$.main(Gatling.scala:39)
        at io.gatling.app.Gatling.main(Gatling.scala)
Caused by: java.lang.ClassNotFoundException: BasicSimulation.scala
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.gatling.app.Selection$Selector.$anonfun$singleSimulationFromConfig$2(Selection.scala:70)
        at scala.util.Try$.apply(Try.scala:209)
        at io.gatling.app.Selection$Selector.findUserDefinedSimulationInClassloader$1(Selection.scala:70)
        ... 15 more

> Task :gatlingRun-BasicSimulation.scala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gatlingRun-BasicSimulation.scala'.
> Some simulations failed : BasicSimulation.scala

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
3 actionable tasks: 1 executed, 2 up-to-date

![image](https://user-images.githubusercontent.com/23381847/49237204-a2e12000-f3f5-11e8-9075-a372a520d988.png)

**Comment by eshepelyuk** [comment]
Plz attach a project to the issues, I need to debug on it.

**Comment by mailtoshrb** [comment]
Please download here https://github.com/mailtoshrb/gatling-demo/blob/master/gatling-demo.7z 

Thanks

**Comment by eshepelyuk** [comment]
Please check your source code, and package declaration.
Actually IDEA highlights the warrning.

**Comment by mailtoshrb** [comment]
I have tried removinf scale folder and directly added all my packages under simulations, but still I get folowing error. I can see all my packages are correctly referenced and no error highlighted by intellij.

>> Task :compileGatlingScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGatlingScala'.
> java.lang.StackOverflowError (no error message)

I am still puzzled and what is hte difference in your plugin with version 3.0.2 as i haven't  changed anything with my packages to import.   we could define as many packages as we can under simulations and if they refer each other correctly,  So in my case, All my test scenarios are placed in scenario package and all its executed steps are importing from respective packages of test scenario. it should work right ?

![image](https://user-images.githubusercontent.com/23381847/49369047-601a9300-f6e8-11e8-93db-eed701af76f4.png)

**Comment by eshepelyuk** [comment]
Plz attach this new version of code.

**Comment by mailtoshrb** [comment]
@eshepelyuk I figured out issue is not in latest plugin but in my code base where i have 100 exec statements repeated on purpose for one test to reporduce an issue in our application. But it worked with 0.4.1 version earlier but after upgrading it was throwing above compile error,  Gone through adding one test after another into folder until i found the actual culprit, it was tedious but worked.                     
Could you  please confirm- does this plugin gets latest version of gatling by itself or we need to look for this plugin updates as well with every version of gatling?
